services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://lab.cn00y8o8m69e.us-east-1.rds.amazonaws.com:3306/portaldoacao?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - spring.datasource.username=admin
      - spring.datasource.password=bancodedados
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.properties.hibernate.format_sql=true
      - debug=true
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
